[project]
name = "nvmath-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.9",
    "matplotlib>=3.10.7",
    "nvmath-python[cpu,cu12,dx]>=0.6.0",
    "pillow>=12.0.0",
    "scipy>=1.16.2",
]
